# Solving the differential equations

In [1]:
import sympy as sp

# Define symbols
t, T, gamma, epsilon, alpha, sigma, l = sp.symbols('t T gamma epsilon alpha sigma l')
lambda1, lambda2, lambda3, lambda4 = sp.symbols('lambda1 lambda2 lambda3 lambda4')
u1, u2 = sp.symbols('u1 u2')
v1, v2 = sp.symbols('v1 v2')
Wt = sp.symbols('Wt')
p1, p2 = sp.symbols('p1 p2')

# Define L function
def L(x, u):
    return ((1/T - p2**2) * sp.DiracDelta(t - T) * sp.exp(-T/gamma) - 
            epsilon * sp.exp(-t/gamma) / l * ((1 - alpha) * (u[0]**2)/2 + alpha * (u[1]**2)/2))

# Define H function
def H(t, x, lambdas, u):
    return (lambdas[0] * v1 + lambdas[1] * (v2 + sp.Abs(u[0])**2 * sigma * Wt) + 
            lambdas[2] * u[0] + lambdas[3] * u[1] - L(x, u))

# Differentiate H with respect to lambdas, v's, p's, and u's
variables = [lambda1, lambda2, lambda3, lambda4, v1, v2, p1, p2, u1, u2]
derivatives = []

for var in variables:
    derivative = sp.diff(H(t, None, [lambda1, lambda2, lambda3, lambda4], [u1, u2]), var)
    derivatives.append(derivative)

# Display derivatives
for var, derivative in zip(variables, derivatives):
    print(f"dH/d{var} = {derivative}")


dH/dlambda1 = v1
dH/dlambda2 = Wt*sigma*Abs(u1)**2 + v2
dH/dlambda3 = u1
dH/dlambda4 = u2
dH/dv1 = lambda1
dH/dv2 = lambda2
dH/dp1 = 0
dH/dp2 = 2*p2*exp(-T/gamma)*DiracDelta(-T + t)
dH/du1 = 2*Wt*lambda2*sigma*(re(u1)*Derivative(re(u1), u1) + im(u1)*Derivative(im(u1), u1))*Abs(u1)*sign(u1)/u1 + epsilon*u1*(1 - alpha)*exp(-t/gamma)/l + lambda3
dH/du2 = alpha*epsilon*u2*exp(-t/gamma)/l + lambda4


In [2]:
# Print derivatives in LaTeX format
for var, derivative in zip(variables, derivatives):
    print(f"\\frac{{\\partial H}}{{\\partial {sp.latex(var)}}} = {sp.latex(derivative)}")


\frac{\partial H}{\partial \lambda_{1}} = v_{1}
\frac{\partial H}{\partial \lambda_{2}} = Wt \sigma \left|{u_{1}}\right|^{2} + v_{2}
\frac{\partial H}{\partial \lambda_{3}} = u_{1}
\frac{\partial H}{\partial \lambda_{4}} = u_{2}
\frac{\partial H}{\partial v_{1}} = \lambda_{1}
\frac{\partial H}{\partial v_{2}} = \lambda_{2}
\frac{\partial H}{\partial p_{1}} = 0
\frac{\partial H}{\partial p_{2}} = 2 p_{2} e^{- \frac{T}{\gamma}} \delta\left(- T + t\right)
\frac{\partial H}{\partial u_{1}} = \frac{2 Wt \lambda_{2} \sigma \left(\operatorname{re}{\left(u_{1}\right)} \frac{d}{d u_{1}} \operatorname{re}{\left(u_{1}\right)} + \operatorname{im}{\left(u_{1}\right)} \frac{d}{d u_{1}} \operatorname{im}{\left(u_{1}\right)}\right) \left|{u_{1}}\right| \operatorname{sign}{\left(u_{1} \right)}}{u_{1}} + \frac{\epsilon u_{1} \cdot \left(1 - \alpha\right) e^{- \frac{t}{\gamma}}}{l} + \lambda_{3}
\frac{\partial H}{\partial u_{2}} = \frac{\alpha \epsilon u_{2} e^{- \frac{t}{\gamma}}}{l} + \lambda_{4}


## Same exercise but considering all variables to be real

In [3]:
import sympy as sp

# Define symbols
t, T, gamma, epsilon, alpha, sigma, l = sp.symbols('t T gamma epsilon alpha sigma l', real=True)
lambda1, lambda2, lambda3, lambda4 = sp.symbols('lambda1 lambda2 lambda3 lambda4', real=True)
u1, u2 = sp.symbols('u1 u2', real=True)
v1, v2 = sp.symbols('v1 v2', real=True)
Wt = sp.symbols('Wt', real=True)
p1, p2 = sp.symbols('p1 p2', real=True)

# Define L function
def L(x, u):
    return ((1/T - x[1]**2) * sp.DiracDelta(t - T) * sp.exp(-T/gamma) - 
            epsilon * sp.exp(-t/gamma) / l * ((1 - alpha) * (u[0]**2)/2 + alpha * (u[1]**2)/2))

# Define H function
def H(t, x, lambdas, u):
    return (lambdas[0] * x[2] + lambdas[1] * (x[3] + sp.Abs(u[0])**2 * sigma * Wt) + 
            lambdas[2] * u[0] + lambdas[3] * u[1] - L(x, u))

# Differentiate H with respect to lambdas, v's, p's, and u's
variables = [lambda1, lambda2, lambda3, lambda4, v1, v2, p1, p2, u1, u2]
derivatives = []

for var in variables:
    derivative = sp.diff(H(t, [p1, p2, v1, v2], [lambda1, lambda2, lambda3, lambda4], [u1, u2]), var)
    derivatives.append(derivative)

# Display derivatives
for var, derivative in zip(variables, derivatives):
    print(f"dH/d{var} = {derivative}")


dH/dlambda1 = v1
dH/dlambda2 = Wt*sigma*u1**2 + v2
dH/dlambda3 = u1
dH/dlambda4 = u2
dH/dv1 = lambda1
dH/dv2 = lambda2
dH/dp1 = 0
dH/dp2 = 2*p2*exp(-T/gamma)*DiracDelta(-T + t)
dH/du1 = 2*Wt*lambda2*sigma*u1 + epsilon*u1*(1 - alpha)*exp(-t/gamma)/l + lambda3
dH/du2 = alpha*epsilon*u2*exp(-t/gamma)/l + lambda4


In [4]:
# Print derivatives in LaTeX format
for var, derivative in zip(variables, derivatives):
    print(f"\\frac{{\\partial H}}{{\\partial {sp.latex(var)}}} = {sp.latex(derivative)}")


\frac{\partial H}{\partial \lambda_{1}} = v_{1}
\frac{\partial H}{\partial \lambda_{2}} = Wt \sigma u_{1}^{2} + v_{2}
\frac{\partial H}{\partial \lambda_{3}} = u_{1}
\frac{\partial H}{\partial \lambda_{4}} = u_{2}
\frac{\partial H}{\partial v_{1}} = \lambda_{1}
\frac{\partial H}{\partial v_{2}} = \lambda_{2}
\frac{\partial H}{\partial p_{1}} = 0
\frac{\partial H}{\partial p_{2}} = 2 p_{2} e^{- \frac{T}{\gamma}} \delta\left(- T + t\right)
\frac{\partial H}{\partial u_{1}} = 2 Wt \lambda_{2} \sigma u_{1} + \frac{\epsilon u_{1} \cdot \left(1 - \alpha\right) e^{- \frac{t}{\gamma}}}{l} + \lambda_{3}
\frac{\partial H}{\partial u_{2}} = \frac{\alpha \epsilon u_{2} e^{- \frac{t}{\gamma}}}{l} + \lambda_{4}


### Finding the optimal controller:

In [5]:
# Define derivatives from previous calculations with u1 being real
dH_du1 = 2*Wt*lambda2*sigma*u1 + epsilon*u1*(1 - alpha)*sp.exp(-t/gamma)/l + lambda3
dH_du2 = alpha * epsilon * u2 * sp.exp(-t / gamma) / l + lambda4

# Solve the system of equations
solution = sp.solve([dH_du1, dH_du2], [u1, u2])

# Print the solution
print("Solution for u1 and u2:")
for u, value in solution.items():
    print(f"{sp.latex(u)} = {sp.latex(value)}")

Solution for u1 and u2:
u_{1} = - \frac{l \lambda_{3} e^{\frac{t}{\gamma}}}{2 Wt l \lambda_{2} \sigma e^{\frac{t}{\gamma}} - \alpha \epsilon + \epsilon}
u_{2} = - \frac{l \lambda_{4} e^{\frac{t}{\gamma}}}{\alpha \epsilon}


Let's compute the Hessian matrix for the function `H` and evaluate its eigenvalues to determine the nature of the critical points. Here's the code:

In [6]:
# Define Hessian matrix
Hessian = sp.zeros(2)

# Define H function
#H = lambda2 * (sp.Abs(u1)**2 * sigma * Wt + sp.re(u1)**2 + sp.im(u1)**2) / u1**2 * sp.Abs(u1) * sp.sign(u1) + epsilon * u1 * (1 - alpha) * sp.exp(-t / gamma) / l
Hessian[0, 0] = sp.diff(H(t, [p1, p2, v1, v2], [lambda1, lambda2, lambda3, lambda4], [u1, u2]), u1, u1)
Hessian[0, 1] = sp.diff(H(t, [p1, p2, v1, v2], [lambda1, lambda2, lambda3, lambda4], [u1, u2]), u1, u2)
Hessian[1, 0] = sp.diff(H(t, [p1, p2, v1, v2], [lambda1, lambda2, lambda3, lambda4], [u1, u2]), u2, u1)
Hessian[1, 1] = sp.diff(H(t, [p1, p2, v1, v2], [lambda1, lambda2, lambda3, lambda4], [u1, u2]), u2, u2)

# Compute eigenvalues
eigenvalues = Hessian.eigenvals()

# Print eigenvalues
print("Eigenvalues of the Hessian matrix:")
for eigenvalue in eigenvalues:
    print(sp.latex(eigenvalue))

Eigenvalues of the Hessian matrix:
\frac{\left(2 Wt l \lambda_{2} \sigma e^{\frac{t}{\gamma}} - \alpha \epsilon + \epsilon\right) e^{- \frac{t}{\gamma}}}{l}
\frac{\alpha \epsilon e^{- \frac{t}{\gamma}}}{l}


In [7]:
# Check if all eigenvalues are negative
all_negative = all(eigval.is_negative for eigval in eigenvalues)

In [8]:
# Print the result
if all_negative:
    print("The Hessian matrix is negative definite.")
else:
    print("The Hessian matrix is not negative definite.")

The Hessian matrix is not negative definite.


Including the expressions for the optimal controller in the combined differential equations drown from the Pontryagin's theorem we get the differential system fully describing our dynamical model, this is 

In [9]:
solution.items()

dict_items([(u1, -l*lambda3*exp(t/gamma)/(2*Wt*l*lambda2*sigma*exp(t/gamma) - alpha*epsilon + epsilon)), (u2, -l*lambda4*exp(t/gamma)/(alpha*epsilon))])

In [8]:
# Define expressions for u1 and u2 from the previous solution
u1_expr =  -l*lambda3*sp.exp(t/gamma)/(2*Wt*l*lambda2*sigma*sp.exp(t/gamma) - alpha*epsilon + epsilon)
u2_expr = -l*lambda4*sp.exp(t/gamma)/(alpha*epsilon)

In [10]:
# Substitute values of u1 and u2 into derivatives
for i, var in enumerate([u1, u2]):
    for j, derivative in enumerate(derivatives):
        derivatives[j] = derivative.subs({var: u1_expr if i == 0 else u2_expr})

# Display substituted derivatives
print("\nSubstituted derivatives:")
for var, derivative in zip(variables, derivatives):
    print(f"dH/d{var} = {derivative.simplify()}")


Substituted derivatives:
dH/dlambda1 = v1


dH/dlambda2 = Wt*l**2*lambda3**2*sigma*exp(2*t/gamma)/(2*Wt*l*lambda2*sigma*exp(t/gamma) - alpha*epsilon + epsilon)**2 + v2
dH/dlambda3 = -l*lambda3*exp(t/gamma)/(2*Wt*l*lambda2*sigma*exp(t/gamma) - alpha*epsilon + epsilon)
dH/dlambda4 = -l*lambda4*exp(t/gamma)/(alpha*epsilon)
dH/dv1 = lambda1
dH/dv2 = lambda2
dH/dp1 = 0
dH/dp2 = 2*p2*exp(-T/gamma)*DiracDelta(T - t)
dH/du1 = 0
dH/du2 = 0


In [11]:
# Print derivatives in LaTeX format
for var, derivative in zip(variables, derivatives):
    print(f"\\frac{{\\partial H}}{{\\partial {sp.latex(var)}}} = {sp.latex(derivative)}")

\frac{\partial H}{\partial \lambda_{1}} = v_{1}
\frac{\partial H}{\partial \lambda_{2}} = \frac{Wt l^{2} \lambda_{3}^{2} \sigma e^{\frac{2 t}{\gamma}}}{\left(2 Wt l \lambda_{2} \sigma e^{\frac{t}{\gamma}} - \alpha \epsilon + \epsilon\right)^{2}} + v_{2}
\frac{\partial H}{\partial \lambda_{3}} = - \frac{l \lambda_{3} e^{\frac{t}{\gamma}}}{2 Wt l \lambda_{2} \sigma e^{\frac{t}{\gamma}} - \alpha \epsilon + \epsilon}
\frac{\partial H}{\partial \lambda_{4}} = - \frac{l \lambda_{4} e^{\frac{t}{\gamma}}}{\alpha \epsilon}
\frac{\partial H}{\partial v_{1}} = \lambda_{1}
\frac{\partial H}{\partial v_{2}} = \lambda_{2}
\frac{\partial H}{\partial p_{1}} = 0
\frac{\partial H}{\partial p_{2}} = 2 p_{2} e^{- \frac{T}{\gamma}} \delta\left(- T + t\right)
\frac{\partial H}{\partial u_{1}} = - \frac{2 Wt l \lambda_{2} \lambda_{3} \sigma e^{\frac{t}{\gamma}}}{2 Wt l \lambda_{2} \sigma e^{\frac{t}{\gamma}} - \alpha \epsilon + \epsilon} - \frac{\epsilon \lambda_{3} \cdot \left(1 - \alpha\right)}{2 Wt l \lam

Now we solve the syste of 8 differential equations with the optimal controller substitued. 

Notice that we are assuming all the initial conditions to be 0. For the case of the position and velocity, these are our assumptions. However, for the case of the $\lambda$'s, how do we stablish the criterion for the initial conditions?

In [16]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Define the system of differential equations
def system(y, t):
    lambda1, lambda2, lambda3, lambda4, p1, p2, v1, v2 = y
    
    # Define derivatives with substituted expressions for u1 and u2
    dH_dlambda1 = v1
    dH_dlambda2 = Wt*l**2*lambda3**2*sigma*sp.exp(2*t/gamma)/(2*Wt*l*lambda2*sigma*sp.exp(t/gamma) - alpha*epsilon + epsilon)**2 + v2
    dH_dlambda3 = -l*lambda3*sp.exp(t/gamma)/(2*Wt*l*lambda2*sigma*sp.exp(t/gamma) - alpha*epsilon + epsilon)
    dH_dlambda4 = -l*lambda4*sp.exp(t/gamma)/(alpha*epsilon)
    dH_dp1 = 0
    dH_dp2 = -2*p2*sp.exp(-T/gamma)*sp.DiracDelta(T - t)
    dH_dv1 = -lambda1
    dH_dv2 = -lambda2
    
    return [dH_dlambda1, dH_dlambda2, dH_dlambda3, dH_dlambda4, dH_dp1, dH_dp2, dH_dv1, dH_dv2]

t_span = np.linspace(0, 10, 100)

# Initial conditions
initial_conditions = [0, 0, 0, 0, 0, 0, 0, 0]

# Solve the system of differential equations
solution = odeint(system, initial_conditions, t_span)

# Print the solution
print("Solution:")
print(solution)

In /Users/flaviaferrusmarimon/anaconda3/lib/python3.9/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Users/flaviaferrusmarimon/anaconda3/lib/python3.9/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Users/flaviaferrusmarimon/anaconda3/lib/python3.9/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /Users/flaviaferrusmarimon/anaconda3/lib/python3.9/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /

Solution:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0

Pinta una mica malament :/

Pot ser sí que amerita fer el cas més simple possible a mà (apollat amb revisió python) i llavors comprovar que tot funcioni si el *optimal controller* realment maximitza el Hamiltonià. 

## Differential equations system: for the simplest case (Linear not Stochastic generating system)

In [17]:
import sympy as sp

# Define symbols
t, T, gamma, epsilon, alpha, sigma, l = sp.symbols('t T gamma epsilon alpha sigma l', real=True)
lambda1, lambda2, lambda3, lambda4 = sp.symbols('lambda1 lambda2 lambda3 lambda4', real=True)
u1, u2 = sp.symbols('u1 u2', real=True)
v1, v2 = sp.symbols('v1 v2', real=True)
p1, p2 = sp.symbols('p1 p2', real=True)

# Define L function
def L(x, u):
    return (1/T * sp.exp(-T/gamma) - 
            epsilon * sp.exp(-t/gamma) / l * ((1 - alpha) * (u[0]**2)/2 + alpha * (u[1]**2)/2))

# Define H function
def H(t, x, lambdas, u):
    return (lambdas[0] * x[2] + lambdas[1] * x[3] + 
            lambdas[2] * u[0] + lambdas[3] * u[1] - L(x, u))

# Differentiate H with respect to lambdas, v's, p's, and u's
variables = [lambda1, lambda2, lambda3, lambda4, v1, v2, p1, p2, u1, u2]
derivatives = []

for var in variables:
    derivative = sp.diff(H(t, [p1, p2, v1, v2], [lambda1, lambda2, lambda3, lambda4], [u1, u2]), var)
    derivatives.append(derivative)

# Display derivatives
for var, derivative in zip(variables, derivatives):
    print(f"dH/d{var} = {derivative}")


dH/dlambda1 = v1
dH/dlambda2 = v2
dH/dlambda3 = u1
dH/dlambda4 = u2
dH/dv1 = lambda1
dH/dv2 = lambda2
dH/dp1 = 0
dH/dp2 = 0
dH/du1 = epsilon*u1*(1 - alpha)*exp(-t/gamma)/l + lambda3
dH/du2 = alpha*epsilon*u2*exp(-t/gamma)/l + lambda4


In [19]:
# Define derivatives from previous calculations with u1 being real
dH_du1 = epsilon*u1*(1 - alpha)*sp.exp(-t/gamma)/l + lambda3
dH_du2 = alpha * epsilon * u2 * sp.exp(-t / gamma) / l + lambda4

# Solve the system of equations
solution = sp.solve([dH_du1, dH_du2], [u1, u2])

# Print the solution
print("Solution for u1 and u2:")
for u, value in solution.items():
    print(f"{sp.latex(u)} = {sp.latex(value)}")

Solution for u1 and u2:
u_{1} = \frac{l \lambda_{3} e^{\frac{t}{\gamma}}}{\alpha \epsilon - \epsilon}
u_{2} = - \frac{l \lambda_{4} e^{\frac{t}{\gamma}}}{\alpha \epsilon}


In [20]:
# Define Hessian matrix
Hessian = sp.zeros(2)

# Define H function
#H = lambda2 * (sp.Abs(u1)**2 * sigma * Wt + sp.re(u1)**2 + sp.im(u1)**2) / u1**2 * sp.Abs(u1) * sp.sign(u1) + epsilon * u1 * (1 - alpha) * sp.exp(-t / gamma) / l
Hessian[0, 0] = sp.diff(H(t, [p1, p2, v1, v2], [lambda1, lambda2, lambda3, lambda4], [u1, u2]), u1, u1)
Hessian[0, 1] = sp.diff(H(t, [p1, p2, v1, v2], [lambda1, lambda2, lambda3, lambda4], [u1, u2]), u1, u2)
Hessian[1, 0] = sp.diff(H(t, [p1, p2, v1, v2], [lambda1, lambda2, lambda3, lambda4], [u1, u2]), u2, u1)
Hessian[1, 1] = sp.diff(H(t, [p1, p2, v1, v2], [lambda1, lambda2, lambda3, lambda4], [u1, u2]), u2, u2)

# Compute eigenvalues
eigenvalues = Hessian.eigenvals()

# Print eigenvalues
print("Eigenvalues of the Hessian matrix:")
for eigenvalue in eigenvalues:
    print(sp.latex(eigenvalue))

Eigenvalues of the Hessian matrix:
- \frac{\epsilon \left(\alpha - 1\right) e^{- \frac{t}{\gamma}}}{l}
\frac{\alpha \epsilon e^{- \frac{t}{\gamma}}}{l}
